export const KPOP_SERVICE_WORKER_NEW_CONTENT = 'KPOP_SERVICE_WORKER_NEW_CONTENT';
export const KPOP_SERVICE_WORKER_READY = 'KPOP_SERVICE_WORKER_READY';
export const KPOP_SERVICE_WORKER_ERROR = 'KPOP_SERVICE_WORKER_ERROR';
export const KPOP_SERVICE_WORKER_OFFLINE = 'KPOP_SERVICE_WORKER_OFFLINE';
